Fix delete old tags query on PostgreSQL
Was failing with:

SequelizeDatabaseError: missing FROM-clause entry for table "Tags"

which notably happens on article updates.

Fix https://github.com/cirosantilli/node-express-sequelize-nextjs-realworld-example-app/issues/19